# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4408f08713bdb828b3dfc3e72c2d237cd9a0c7a678975fa7def994bac567fd29711fa513a7c8f3ad909f0c370a00500b2e02dea0b87289c721f6fb89c9fda90c

test:
  secret_key_base: 32be90ec5130cc1dc30333a799d4b9e24660ba9c9e1c3c24d0f80b768e3ac30fae693ffac9d798aa81f720c1143904f23639440e37cc2fb575953ee2e2375112

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
